package store

import "database/sql"

// State represents a message's lifecycle position in the queue.
type State string

const (
	StateQueued     State = "queued"
	StateDelivering State = "delivering"
	StateDelivered  State = "delivered"
	StateFailed     State = "failed"
)

// Kind distinguishes a paste-rendered chat message from a control command
// that is typed directly into the recipient pane.
type Kind string

const (
	KindMessage Kind = "message"
	KindControl Kind = "control"
	// KindDeliveryFailureNotice marks a message auto-generated by the
	// mailman when one of the recipient's outbound messages transitioned
	// to a terminal-failure state. The kind is the load-bearing
	// loop-prevention marker (per #53): a notice that itself fails to
	// deliver MUST NOT generate another notice — otherwise a wedged
	// pane on either side would burn the message queue. The mailman's
	// failure-hook checks the failed message's kind before generating
	// and silently skips notices.
	KindDeliveryFailureNotice Kind = "delivery_failure_notice"
	// KindStrandedDraft marks a message auto-generated by the mailman
	// when the observe-gate (#92) flushes operator-typed content out of
	// the input row to make room for delivery. The cleared content is
	// snapshotted as a stranded_draft row addressed back to the agent
	// so the operator can recover their typed work after the fact. Per
	// the (c) Clear-paste-archive flush semantics agreed at #92's
	// 2026-06-04 design comment: explicitly preferred over (b)
	// Clear-and-discard because the input row's content may itself be a
	// half-delivered bus message from a previous failed delivery (paste
	// succeeded but verify-token never landed); blind Ctrl+U would
	// destroy bus content not operator content.
	KindStrandedDraft Kind = "stranded_draft"
)

// Message mirrors a row in the messages table. Timestamps are kept as
// strings (ISO 8601 UTC) — callers parse to time.Time at presentation time
// if needed; the store layer is timezone-agnostic.
type Message struct {
	ID          int64
	PublicID    string
	FromAgent   string
	ToAgent     string
	ReplyTo     sql.NullString
	Body        string
	Kind        Kind
	State       State
	CreatedAt   string
	DeliveredAt sql.NullString
	Error       sql.NullString
}

// Agent mirrors a row in the agents table.
type Agent struct {
	Name      string
	PaneID    string // empty when pane_id is NULL
	Paused    bool
	UpdatedAt string
	// Aliases is the JSON-decoded list of alternative names the
	// discover walker should accept for this canonical agent. Empty
	// list when no aliases registered. See #38.
	Aliases []string
}
