package store

import "database/sql"

// State represents a message's lifecycle position in the queue.
type State string

const (
	StateQueued       State = "queued"
	StateDelivering   State = "delivering"
	StateDelivered    State = "delivered"
	StateFailed       State = "failed"
	StateAcknowledged State = "acknowledged" // #221: operator-acked announce-skipped backlog residue
	// StateDeferred is a pre-`queued` holding state (#227): the row exists
	// but is not yet eligible for mailman pickup. It carries a non-empty
	// deliver_after trigger and is promoted to `queued` when that trigger
	// fires (a flush_deferred call). Deferred rows are invisible to
	// ClaimNext / inbox / mailman until promoted — the deferral lives in
	// `state`, not in delivery-cadence policy, so the mailman stays eager
	// and the single-writer invariant is untouched.
	StateDeferred State = "deferred"
)

// Kind distinguishes a paste-rendered chat message from a control command
// that is typed directly into the recipient pane.
type Kind string

const (
	KindMessage Kind = "message"
	KindControl Kind = "control"
	// KindDeliveryFailureNotice marks a message auto-generated by the
	// mailman when one of the recipient's outbound messages transitioned
	// to a terminal-failure state. The kind is the load-bearing
	// loop-prevention marker (per #53): a notice that itself fails to
	// deliver MUST NOT generate another notice — otherwise a wedged
	// pane on either side would burn the message queue. The mailman's
	// failure-hook checks the failed message's kind before generating
	// and silently skips notices.
	KindDeliveryFailureNotice Kind = "delivery_failure_notice"
	// KindStrandedDraft marks a message auto-generated by the mailman
	// when the observe-gate (#92) flushes operator-typed content out of
	// the input row to make room for delivery. The cleared content is
	// snapshotted as a stranded_draft row addressed back to the agent
	// so the operator can recover their typed work after the fact. Per
	// the (c) Clear-paste-archive flush semantics agreed at #92's
	// 2026-06-04 design comment: explicitly preferred over (b)
	// Clear-and-discard because the input row's content may itself be a
	// half-delivered bus message from a previous failed delivery (paste
	// succeeded but verify-token never landed); blind Ctrl+U would
	// destroy bus content not operator content.
	KindStrandedDraft Kind = "stranded_draft"
	// KindPing marks a substrate-only reachability probe (#144). The
	// mailman picks the row up like any other message — which itself
	// proves the daemon is alive — but instead of paste-and-Enter it
	// runs substrate-health checks (recipient registered, pane live)
	// and transitions the row straight to delivered (healthy) or
	// failed (unreachable). The whole point is to exercise the
	// DB-insert → mailman-pickup → delivery-state path WITHOUT pasting
	// into the recipient's pane: a "is the daemon up + agent reachable?"
	// probe that loads no recipient context.
	KindPing Kind = "ping"
	// KindDedupeNotice marks a message auto-generated by the mailman when
	// the dedupe path absorbs a replay (#157 PR2): the original
	// delivered_in_input_box message was re-verified as confirmed and the
	// replay was dropped. The notice travels back to the original sender
	// as a positive resolution signal — distinct from KindDeliveryFailureNotice
	// which signals a failure.
	KindDedupeNotice Kind = "dedupe_notice"
	// KindBacklogAnnounce marks the synthetic "📬 N queued — run inbox"
	// nudge the register handler inserts when an agent (re)registers with a
	// queued backlog (#204). Like the other synthetic kinds it rides the
	// normal mailman loop (single-writer-safe — the register process never
	// pastes), but its body is a one-shot heads-up, not bus content: it tells
	// a freshly-restarted session it has mail waiting without the mailman
	// flooding the pane with the whole pre-existing backlog at once.
	KindBacklogAnnounce Kind = "backlog_announce"
)

// Message mirrors a row in the messages table. Timestamps are kept as
// strings (ISO 8601 UTC) — callers parse to time.Time at presentation time
// if needed; the store layer is timezone-agnostic.
type Message struct {
	ID              int64
	PublicID        string
	FromAgent       string
	ToAgent         string
	ReplyTo         sql.NullString
	Body            string
	Kind            Kind
	NoReplyExpected bool
	Quick           bool // compact single-line chrome (#154)
	State           State
	CreatedAt       string
	DeliveredAt     sql.NullString
	Error           sql.NullString
	// Replay linkage (#157 PR1), set only on messages created by `resend`.
	// ReplayOf is the original message's public_id; ReplayOfAt is the
	// original's created_at (ISO 8601 UTC) — carried on the row so the pure
	// render layer can show the "Replayed: original sent at <ts>" marker
	// without a store lookup. Both invalid/empty for normal messages.
	ReplayOf   sql.NullString
	ReplayOfAt sql.NullString
	// DeliverAfter mirrors the #227 `deliver_after` column: the trigger that
	// promotes a deferred row to `queued`. Non-empty only on rows in
	// StateDeferred (the trigger name, e.g. "resume"); NULL/invalid for normal
	// messages. Read for visibility (`sent --deferred`); the promotion itself
	// matches on the column via SQL, not this field.
	DeliverAfter sql.NullString
	// Verified mirrors the #169 `verified` column. 1 = verify-token observed
	// (confirmed delivery), 0 = delivered_in_input_box soft-fail (paste landed,
	// token never surfaced), NULL/invalid = pre-migration row or not yet
	// delivered. Orthogonal to State: both verified and unverified rows carry
	// State == StateDelivered.
	Verified sql.NullInt64
}

// Agent mirrors a row in the agents table.
type Agent struct {
	Name      string
	PaneID    string // empty when pane_id is NULL
	Paused    bool
	UpdatedAt string
	// Aliases is the JSON-decoded list of alternative names the
	// discover walker should accept for this canonical agent. Empty
	// list when no aliases registered. See #38.
	Aliases []string
	// DeliveryMode controls how the mailman delivers to this agent
	// (#116). Two values:
	//   - "paste-and-enter" (default): mailman delivers via tmux paste
	//     + Enter; the existing behavior for CLI-tool-hosting panes.
	//   - "mailbox-only": mailman does NOT paste; messages stay in
	//     state=queued and the operator polls via `claude-msg inbox`.
	//     The operator-as-bus-participant scenario from ADR-0005
	//     §Decision (1)'s wheel-reinvention check.
	// Default for newly-inserted agents (and the back-compat ALTER's
	// DEFAULT) is "paste-and-enter".
	DeliveryMode string
	// BacklogEpoch is the #204 claim-floor: the highest message id that
	// counts as pre-existing backlog at the agent's last (re)register.
	// The mailman's ClaimNext skips queued rows with id <= this value, so
	// a freshly-restarted session is not flooded with its whole backlog.
	// Invalid (NULL) when the agent has never registered with a queued
	// backlog — ClaimNext treats that as "no floor" (deliver everything).
	// Stamped by the register handler via SetBacklogEpoch; see #204.
	BacklogEpoch sql.NullInt64
	// AttentionState is the chamber → operator attention signal (#224).
	// Three values: "idle" (default; no operator action pending), "busy"
	// (chamber mid-tool-call; informational), "awaiting_operator" (chamber
	// has presented a choice/question and needs the operator to weigh in).
	// Set explicitly by chambers via flag_operator / clear_operator_flag.
	// Auto-cleared to "idle" on the chamber's next register call.
	AttentionState string
}

// Delivery-mode constants. Constrained string set; see Agent.DeliveryMode
// for semantics. The store does not enforce membership at insert-time;
// callers should validate via ValidDeliveryMode before writing.
const (
	DeliveryModePasteAndEnter = "paste-and-enter"
	DeliveryModeMailboxOnly   = "mailbox-only"
)

// ValidDeliveryMode reports whether s is a known delivery-mode value.
// Empty string is treated as INVALID (callers should default to
// DeliveryModePasteAndEnter explicitly rather than relying on zero-
// value behavior to leak into the schema).
func ValidDeliveryMode(s string) bool {
	return s == DeliveryModePasteAndEnter || s == DeliveryModeMailboxOnly
}

// Attention-state constants (#224). Constrained string set; the store
// does not enforce membership at insert-time, so callers should validate
// via ValidAttentionState before writing.
const (
	// AttentionStateIdle is the default — chamber reachable; no operator
	// action pending. Set by register auto-clear when a chamber comes
	// back from /compact, restart, or a normal (re)register.
	AttentionStateIdle = "idle"
	// AttentionStateBusy is the informational mid-tool-call signal. Not
	// actively used by any substrate-side mechanism today; reserved for
	// future hook-driven auto-tracking.
	AttentionStateBusy = "busy"
	// AttentionStateAwaitingOperator is the load-bearing case: the
	// chamber has presented a choice or question and is waiting for the
	// operator to weigh in. Set by flag_operator, cleared by
	// clear_operator_flag or by the chamber's next register.
	AttentionStateAwaitingOperator = "awaiting_operator"
)

// ValidAttentionState reports whether s is a known attention-state value.
// Empty string is treated as INVALID (callers should default to
// AttentionStateIdle explicitly rather than relying on zero-value
// behavior to leak into the schema).
func ValidAttentionState(s string) bool {
	return s == AttentionStateIdle ||
		s == AttentionStateBusy ||
		s == AttentionStateAwaitingOperator
}

// ReservedRoutingName reports whether name is reserved as a routing
// primitive (a virtual recipient resolved at delivery-prep time) and
// therefore cannot be registered as a real agent name or alias.
//
// Routing primitives:
//   - "operator" (#228) — resolves to the chamber the operator is
//     currently or was most-recently attached to. A real chamber
//     registering as "operator" would shadow the resolver: the
//     send-side substitution would match against the literal name
//     before ever calling into resolveOperatorTarget, and a phantom
//     chamber could harvest operator-directed traffic.
//
// Other reserved names like "operator-attention" (#224) are NOT in
// this list because they ARE real recipients (the operator pre-
// registers them as mailbox-only agents); they are reserved by
// convention, not by substrate enforcement.
//
// ErrReservedRoutingName is the error returned when a reserved name
// is attempted; callers should surface it to the operator as a clear
// "pick a different name" signal.
func ReservedRoutingName(name string) bool {
	return name == "operator"
}
